<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Official Transcript - Barani Institute</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            line-height: 1.6;
            margin: 40px;
            color: #000;
            position: relative; /* Ensure positioning context for watermark */
        }
        .header {
            text-align: center;
            margin-bottom: 30px;
        }
        .header h1 {
            margin: 0;
            font-size: 28px;
            color: #015d05;
        }
        .header h2 {
            margin: 0;
            font-size: 20px;
        }
        .student-info {
            width: 100%;
            margin-bottom: 20px;
        }
        .student-info td {
            padding: 5px;
            width: 50%; /* Two columns */
        }
        .session-container {
            margin-bottom: 20px;
            border: 1px solid #000;
            padding: 10px;
        }
        .subjects-table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 10px;
        }
        .subjects-table th, .subjects-table td {
            border: 1px solid #000;
            padding: 8px;
            text-align: left;
        }
        .subjects-table th {
            background-color: #f2f2f2;
        }
        .session-header {
            margin-bottom: 10px;
            font-weight: bold;
            font-size: 18px;
        }
        .gpa-info {
            margin-top: 10px;
            font-weight: bold;
        }

        /* Watermark Style */
        .watermark {
            position: absolute;
            top: 50%;
            left: 50%;
            transform: translate(-50%, -50%) rotate(-45deg);
            font-size: 120px;
            color: rgba(0, 0, 0, 0.1); /* Light black for transparency */
            font-weight: bold;
            text-align: center;
            pointer-events: none; /* Prevent watermark from interfering with page elements */
            z-index: -1; /* Ensure watermark is behind other content */
        }

        /* Footer Style */
        footer {
            text-align: center;
            font-size: 16px;
            margin-top: 30px;
        }
        footer .generated-by {
            color: black;
        }
        footer .lms {
            color: rgb(0, 76, 255);
            font-size: 22px; /* Make LMS a little bigger */
        }

    </style>
</head>
<body>
    <div class="watermark">UNOFFICIAL</div>

    <div class="header">
        <h1>BARANI INSTITUTE OF INFORMATION TECHNOLOGY</h1>
        <h2>UN-OFFICIAL TRANSCRIPT OF RECORD</h2>
    </div>

    <table class="student-info">
        <tr>
            <td>Name:<strong> {{ $student->name }}</strong></td>
            <td>Father's Name:<strong> {{ $student->guardian }}</strong></td>
        </tr>
        <tr>
            <td>Registration No: <strong>{{ $student->RegNo }}</strong> </td>
            <td>Date of Birth: <strong>{{ $student->date_of_birth }}</strong> </td>
        </tr>
    </table>

    <p>Program :<strong> {{ $program->description }}</strong></p>

    @foreach ($sessionResults as $session)
        <div class="session-container">
            <div class="session-header">Session: {{ $session['session_name'] }}</div>

            <table class="subjects-table">
                <thead>
                    <tr>
                        <th>Course Name</th>
                        <th>Course Code</th>
                        <th>Credit Hours</th>
                        <th>Grade</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach ($session['subjects'] as $subject)
                        <tr>
                            <td>{{ $subject['course_name'] }}</td>
                            <td>{{ $subject['course_code'] }}</td>
                            <td>{{ $subject['credit_hours'] }}</td>
                            <td>{{ $subject['grade'] }}</td>
                        </tr>
                    @endforeach
                </tbody>
            </table>

            <div class="gpa-info">
                <p><strong>GPA:</strong> {{ $session['GPA'] }}</p>
                <p><strong>Total Credit Points:</strong> {{ $session['total_credit_points'] }}</p>
            </div>
        </div>
    @endforeach

    <!-- Footer -->
    <footer>
        <span class="generated-by">Generated By</span> <span class="lms">LMS</span>
    </footer>
</body>
</html>


